const data = {
    products:[
        {
            _id:'1',
            name:'Kalimooch Rice',
            category: 'Grains',
            image: '/images/Rice.png',
            price:60,
            brand:'RiceBrand',
            rating: 4.5,
            numReviews:102,
            description:'Kalimooch Rice description',
        },
        {
            _id:'2',
            name:'Basmati Rice',
            category: 'Grains',
            image: '/images/Rice.png',
            price:100,
            brand:'Basmati',
            rating: 4.5,
            numReviews:102,
            description:'Basmati Rice description',
        },
        {
            _id:'3',
            name:'Idli Rice',
            category: 'Grains',
            image: '/images/Rice.png',
            price:30,
            brand:'RiceBrand',
            rating: 4.5,
            numReviews:102,
            description:'Idli Rice description',
        },
        {
            _id:'4',
            name:'New Kalimooch Rice',
            category: 'Grains',
            image: '/images/Rice.png',
            price:70,
            brand:'RiceBrand',
            rating: 4.5,
            numReviews:102,
            description:'Brand new Rice description',
        },
        {
            _id:'5',
            name:'Brown Rice',
            category: 'Grains',
            image: '/images/Rice.png',
            price:20,
            brand:'RiceBrand',
            rating: 4.5,
            numReviews:202,
            description:'Brown Rice description',
        },
    ],
}

export default data;